### ISSUE TITLE
pods is forbidden: failed quota

### ISSUE THREAD

**Issue by todaygood** [todaygood/k8s-lab#1]
```bash
[root@k8s0 configmap]# kubectl create -f test-cm.yaml 
Error from server (Forbidden): error when creating "test-cm.yaml": pods "test-configmap" is forbidden: failed quota: compute-resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
[root@k8s0 configmap]# kubectl get resourcequota
NAME                AGE
compute-resources   225d
```

**Comment by todaygood** [comment]
添加quota 
```
   resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
```
最终pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
   name: test-configmap
spec:
  containers:
    - name: test-configmap
      image: busybox
      command: ["bin/sh", "-c","env"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: test-configmap-config
              key: special.how
        - name: TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: test-configmap-config
              key: special.type
      envFrom:
        - configMapRef:
            name: env-config
  restartPolicy: Never
```
成功
```bash
[root@k8s0 configmap]# kubectl create -f test-cm.yaml 
pod "test-configmap" created
```
